App/views.py
# url+视图函数
import random
from operator import or_

from flask import Blueprint, render_template, jsonify, request, redirect, url_for, session
from sqlalchemy import desc

from App.exts import cache
from .models import *

blog = Blueprint('blog', __name__)
admin = Blueprint('admin', __name__)


@blog.route('/')
def home():
    # 用户的个人信息
    user = User.query.all()[0]
    # 查询所有的文章

    arts = Article.query.order_by(desc('is_recommand'))
    # 查询图片
    ablums = PhotoMain.query.all()
    # 查看自己分类
    types = AriticleType.query.all()

    data = {
        "user": user,
        "arts": arts,

        "ablums": ablums,
        "types": types,
    }

    return render_template('blog/index.html', **data)


@blog.route("/info/<id>", methods=["GET", "POST", "PUT", "DELETE"])
def info(id):
    '''
    文章详细内容
    :return:
    '''
    if request.method == "GET":
        article = Article.query.get(id)
        #
        print(article.visit)

        if article.visit:
            article.visit += 1
        else:
            article.visit = 1
        db.session.commit()

        # 获取上一篇和下一篇的内容
        if id != 1:
            prvart = Article.query.filter(Article.id.__lt__(id)).first()
        else:
            prvart = None

        nextart = Article.query.filter(Article.id.__gt__(id)).first()

        # 查询所有的文章
        arts = Article.query.all()
        # 查看自己分类
        types = AriticleType.query.all()
        commands = Commend.query.filter(Commend.articleid == article.id).order_by(desc("time"))

        tags = article.tag.split("、")
        typeclass = []
        tmp = article.ariticletype
        flags = 1
        while flags:
            typeclass.append(tmp.name)
            if tmp.father_type:
                print(tmp.father_type)
                tmp = AriticleType.query.get(tmp.father_type)
            else:
                flags = 0
        print(typeclass)

        data = {
            "prvart": prvart,
            "nextart": nextart,

            "article": article,
            "typeclass": typeclass,

            "tags": tags,
            "arts": arts,
            "commands": list(commands),

            "types": types,
        }
        return render_template("blog/info.html", **data)

    elif request.method == "PUT":
        '''
            修改点赞量。
        '''
        if cache.get(request.remote_addr) != id:
            try:
                id = request.form.get("id")
                cache.set(request.remote_addr, id, 5)
                art = Article.query.get(id)
                art.num += 1
                db.session.commit()
                return jsonify({"code": 1, "art_num": art.num})
            except:
                return jsonify({"code": 0})
        else:
            cache.set(request.remote_addr, id, 5)
            return jsonify({"code": 2})

    elif request.method == "POST":

        try:
            id = request.cookies.get("user") or "1"
            nameip = request.remote_addr
            artid = request.form.get("artid")
            name = request.form.get("name") or nameip
            info = request.form.get("info")

            user = User()

            user.name = name
            user.icon = "http://img4.imgtn.bdimg.com/it/u=2641899507,2178808967&fm=26&gp=0.jpg"
            user.time = datetime.datetime.now()
            db.session.add(user)
            db.session.commit()

            commend = Commend()
            # 反向插入id必须找到对方的值。
            commend.comment_user = user
            commend.articleid = artid
            commend.info = info
            commend.time = datetime.datetime.now()

            db.session.add(commend)
            db.session.commit()

            return jsonify({"code": 1})
        except:
            return jsonify({"code": 0})


@blog.route("/yzm/")
def yzm():
    tmp = "0123456789qwertyuiopasdfghjklzxcvbnm"
    num = ""
    for i in range(4):
        num += random.choice(tmp)
    return jsonify({"code": 1, "yzm": num})


@blog.route("/share/")
def share():
    '''
    图片壁纸的分类
    :return:
    '''

    pages = request.args.get("page", 1)
    per_page = request.args.get("per_page", 12)

    phage = PhotoMain.query.filter_by().paginate(int(pages), int(per_page), error_out=False)
    print(pages)
    data = {
        "phage": phage,
        "selected2": "selected"
    }
    return render_template("blog/share.html", **data)


@blog.route("/share/<id>")
def infopic(id):
    '''
    图片壁纸的分类
    :return:
    '''

    # 用户的个人信息
    user = User.query.all()[0]
    # 查询所有的文章
    arts = Article.query.all()
    # 查询图片
    ablums = PhotoMain.query.all()
    # 查看自己分类
    types = AriticleType.query.all()

    photo = PhotoMain.query.get(id)

    data = {
        "photo": photo,
        "selected2": "selected",

        "user": user,
        "arts": arts,
        "ablums": ablums,
        "types": types,
    }
    return render_template("blog/infopic.html", **data)


@blog.route("/about/")
def about():
    '''
    关于我
    :return:
    '''
    # 用户的个人信息
    user = User.query.all()[0]
    # 查询图片
    ablums = Photo.query.all()
    data = {
        "user": user,
        "ablums": ablums,
        "selected3": "selected"

    }
    return render_template("blog/about.html", **data)


@blog.route("/gbook/")
def gbook():
    '''
    关于我
    :return:
    '''
    # 用户的个人信息
    user = User.query.all()[0]
    # 查询图片
    ablums = Photo.query.all()
    data = {
        "user": user,
        "ablums": ablums,
        "selected4": "selected"

    }
    return render_template("blog/gbook.html", **data)


@blog.route("/type/<id>")
def clicktype(id):
    '''
    点击分类的接口
    :param id:
    :return:
    '''
    articles = AriticleType.query.get(id)
    return jsonify(articles.to_dict())


@blog.route("/articleType/")
def articleType():
    # 查看自己分类
    types = AriticleType.query.all()
    # 查询所有的文章
    arts = Article.query.all()

    page = request.args.get("pages", 1)
    per_page = request.args.get("per_page", 5)
    print(page, per_page)

    artspg = Article.query.paginate(int(page), int(per_page), False).items

    arts_list = [art.to_dict() for art in artspg]
    types_list = [type.to_dict() for type in types]
    data = {
        "types": types_list,
        "arts": arts_list,
        # "artspg":artspg
    }

    return jsonify(data)


# 文章搜索
@blog.route("/searchkey/")
def searchkey():
    # 查询所有的文章
    key = request.args.get("key")
    page = request.args.get("pages", 1)
    per_page = request.args.get("per_page", 5)

    artspg = Article.query.filter(or_(Article.title.contains(key), Article.text.contains(key))).paginate(int(page),
                                                                                                         int(per_page),
                                                                                                         False).items

    arts_list = [art.to_dict() for art in artspg]
    data = {
        "arts": arts_list,
    }

    return jsonify(data)


# ===============管理员摄图===============================

# 管理员的登录页面
@admin.route("/admin/login", methods=["GET", "POST"])
def admin_login():
    if request.method == "GET":
        return render_template("admin/login.html")
    elif request.method == "POST":
        info = request.form
        username = info.get("username")
        userpwd = info.get("userpwd")

        user = list(User.query.filter_by(name=username, password=userpwd))

        if user:
            if user[0].is_super == 1:
                print(user[0].id)

                session["uid"] = user[0].id
                return redirect(url_for('admin.amdin_index'))
            else:
                return render_template("admin/login.html", errors="不是管理员")
        else:
            return render_template("admin/login.html", errors="用户没有注册。")


# 退出登录
@admin.route("/admin/logout", methods=["GET", "POST"])
def admin_logout():
    if request.method == "GET":
        session.pop('uid')
        return redirect(url_for('admin.admin_login'))


# 管理首页
@admin.route('/admin/')
def amdin_index():
    # 获取全部的文章

    if not session.get("uid"):
        return redirect(url_for('admin.admin_login'))

    userid = session.get("uid") or "1"
    uname = User.query.get(userid).name
    comment = Commend.query.all()

    arts = Article.query.filter_by(userid=userid)

    ip = request.remote_addr
    nums = 0
    for num in list(arts):
        nums += num.num

    data = {
        "nums": nums,
        "comment": comment,
        "uname": uname,
        "arts": list(arts),
        "time": str(datetime.datetime.now())[:str(datetime.datetime.now()).rfind(".")],
        "ip": ip,
    }

    return render_template('admin/index.html', **data)


# 文章管理| 删除操作
@admin.route('/article/', methods=["GET", "POST", "PUT", "DELETE"])
def amdin_article():
    if request.method == "GET":
        userid = request.cookies.get("user") or "1"

        page = int(request.args.get("pg", 1))
        per_page = int(request.args.get("per_page", 4))
        arts = Article.query.filter_by(userid=userid).paginate(page, per_page, error_out=False)

        data = {
            "arts": list(arts.items),
            "pgs": arts

        }
        return render_template('admin/article.html', **data)
    elif request.method == "POST":
        try:
            infos = request.form.getlist("checkbox[]")
            for art in infos:
                artid = Article.query.get(art)
                db.session.delete(artid)
                db.session.commit()

            return redirect("/article/")
        except:
            return redirect('/article/?error=删除错误')


# 文章修改管理
@admin.route('/update/<id>', methods=["GET", "POST", "PUT", "DELETE"])
def amdin_update(id):
    if request.method == "GET":
        userid = request.cookies.get("user") or "1"

        arts = Article.query.get(id)
        print(arts)
        data = {
            "arts": arts.to_dict(),
            "arttype": AriticleType.query.all()
        }

        return render_template('admin/update-article.html', **data)

App/templates/blog/base.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
    <meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青"/>
    <meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='blog/css/base.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='blog/css/index.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='blog/css/m.css') }}" rel="stylesheet">

    {% block extcss %}

    {% endblock %}



    <script src="/static/blog/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/blog/js/hc-sticky.js"></script>
    <script type="text/javascript" src="/static/blog/js/comm.js"></script>
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->


    {% block extjs %}

    {% endblock %}
</head>
<body>
<header class="header-navigation" id="header">
    <nav>
        <div class="logo"><a href="/">杨青个人博客</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
            <li><a href="/" id="{{ selected1 }}">首页</a></li>
            <li><a href="{{ url_for('blog.share') }}" id="{{ selected2 }}">相册</a></li>
            <li><a href="{{ url_for('blog.about') }}" id="{{ selected3 }}">关于我</a></li>
            <li><a href="{{ url_for('blog.gbook') }}" id="{{ selected4 }}">留言</a></li>
        </ul>
    </nav>
</header>

{% block content %}

{% endblock %}

</body>
</html>

App/templates/blog/index.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
    <meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青"/>
    <meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='blog/css/base.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='blog/css/index.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='blog/css/m.css') }}" rel="stylesheet">

    <script src="/static/blog/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/blog/js/hc-sticky.js"></script>
    <script type="text/javascript" src="/static/blog/js/comm.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <!--[if lt IE 9]>
    <script src="js/modernizr.js"></script>
    <![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
    <nav>
        <div class="logo"><a href="/">杨青个人博客</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
            <li><a href="/" id="selected">首页</a></li>
            <li><a href="{{ url_for('blog.share') }}">相册</a></li>
            <li><a href="{{ url_for('blog.about') }}">关于我</a></li>
            <li><a href="{{ url_for('blog.gbook') }}">留言</a></li>
        </ul>
    </nav>
</header>
<article id="app">


    <aside class="l_box">
        <div class="about_me">
            <h2>关于我</h2>
            <ul>
                <i><img src="{{ user.icon }}"></i>
                <p><b>{{ user.name }}</b>{{ user.introduction }}</p>


            </ul>
        </div>
        <div class="wdxc">
            <h2>我的相册</h2>
            <ul>
                {% for ablum in ablums %}
                    <li><a href=""><img src="{{ ablum.picture }}" alt=""></a></li>
                {% endfor %}


            </ul>
        </div>
        <div class="search">

            <input v-model="search_key" @keyup.enter="search" name="keyboard" id="keyboard" class="input_text" value="请输入关键字词"
                   placeholder="请输入关键字词" type="text">


            <input name="Submit" @click="search" class="input_submit" value="搜索" type="submit">

        </div>

        <div class="fenlei" r_box>

            <h2>文章分类</h2>
            <ul>

                <li v-for="item in types" :key="item.id">
                    <a href="javascript:;" @click="itemize(item.id)">{[ item.name ]} ( {[ item.articles.length
                        ]})</a>
                </li>

            </ul>
        </div>
        <div class="tuijian">
            <h2>站长推荐</h2>
            <ul>
                {% for art in arts.arts %}
                    {% if art.is_recommand %}
                        <li><a href="/">{{ art.title }}</a></li>
                    {% endif %}
                {% endfor %}


            </ul>
        </div>
        <div class="links">
            <h2>友情链接</h2>
            <ul>
                <a href="https://blog.csdn.net/wuye1015">个人博客</a> <a
                    href="https://blog.csdn.net/wuye1015">wuye24h博客</a>
            </ul>
        </div>
        <div class="guanzhu">
            <h2>关注我 么么哒</h2>
            <ul>
                <img src="/static/blog/images/wx.jpg">
            </ul>
        </div>
    </aside>

    <main class="r_box">

        <li v-for="art in arts">
            <i><a :href="'/info/'+art.id"><img :src="art.picture" alt="百度搜索博客wuye24h">{[ art.title ]}</a></i>
            <h3>


                <span v-if="art.is_recommand" style="color: red">
                    [ 顶 ]
                </span>
                
                <a :href="'/info/'+art.id">{[ art.title ]}</a></h3>
            <p>{[ art.introduce ]}</p>
        </li>

    </main>


</article>
<footer>
    <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>


<script>
    new Vue({
        delimiters: ['{[', ']}'],
        el: "#app",
        data: {
            arts: [],
            types: [],
            pages: 1,
            REQUIRE: true,
            search_key: ""
        },
        created() {
            console.log(this.arts)
            axios.get('/articleType/', {
                "pages": this.pages,
                "per_page": 5
            })
                .then((res) => {
                    this.arts = res.data.arts;
                    this.types = res.data.types;
                    console.log(this.arts)

                })
                .catch(function (error) {
                    console.log(error);
                });
        },
        mounted() {
            this.scroll(this.pages)
        },
        methods: {
            search() {
                console.log("你點擊了")
                if (this.search_key.length>=1) {
                    axios.get('/searchkey/', {
                        params: {
                            "key": this.search_key
                        }
                    })
                        .then((res) => {
                            this.arts = res.data.arts;
                        })
                        .catch(function (error) {
                            console.log(error);
                        });
                }

            },

            itemize(id) {
                axios.get("/type/" + id)
                    .then((res) => {
                        $("#index-aside").css({
                            "position": "relative",
                            "left": "auto",
                            "width": "1000px"
                        });
                        this.arts = res.data.articles;
                        console.log(res.data.articles)

                    })
                    .catch((err) => {

                    })
            },
            scroll(pages) {
                let isLoading = false;
                window.onscroll = () => {
                    // 距离底部200px时加载一次
                    let bottomOfWindow = document.documentElement.offsetHeight - document.documentElement.scrollTop - window.innerHeight <= 200;
                    if (bottomOfWindow && isLoading == false && this.REQUIRE) {
                        isLoading = true;
                        this.pages += 1;
                        axios.get('/articleType/', {
                            params: {
                                "pages": this.pages,
                                "per_page": 5
                            }
                        })
                            .then((res) => {
                                if (res.data.arts.length != 0) {
                                    this.arts = this.arts.concat(res.data.arts);
                                } else {
                                    this.REQUIRE = false;
                                    alert("到底了！！，回去看看吧")
                                }


                                isLoading = false
                            })
                            .catch(function (error) {
                                console.log(error);
                            });

                    }
                }
            },
        }
    })

</script>

App/templates/blog/info.html
{% extends 'blog/base.html' %}

{% block extcss %}
    <link href="/static/blog/css/info.css" rel="stylesheet">
{% endblock %}

{% block content %}



    <article>
        <aside class="l_box">
            <div class="search">
                <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
                    <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词"
                           style="color: rgb(153, 153, 153);"
                           onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}"
                           onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                    <input name="show" value="title" type="hidden">
                    <input name="tempid" value="1" type="hidden">
                    <input name="tbname" value="news" type="hidden">
                    <input name="Submit" class="input_submit" value="搜索" type="submit">
                </form>
            </div>
            <div class="fenlei">
                <h2>文章分类</h2>
                <ul>
                    {% for type in types %}
                        <li><a href="">{{ type.name }} ( {{ type.articles | length }} )</a></li>
                    {% endfor %}


                </ul>
            </div>
            <div class="tuijian">
                <h2>站长推荐</h2>
                <ul>
                    {% for art in arts %}
                        {% if art.is_recommand %}
                            <li><a href="/">{{ art.title }}</a></li>
                        {% endif %}
                    {% endfor %}


                </ul>
            </div>
            <div class="tuijian">
                <h2>点击排行</h2>
                <ul>
                    <li><a href="/">你是什么人便会遇上什么人</a></li>
                    <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
                    <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
                    <li><a href="/">个人博客模板《绅士》后台管理</a></li>
                    <li><a href="/">你是什么人便会遇上什么人</a></li>
                    <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
                    <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
                    <li><a href="/">个人博客模板《绅士》后台管理</a></li>
                </ul>
            </div>
            <div class="cloud">
                <h2>标签云</h2>
                <ul>
                    {% for tag in tags %}
                        <a href="javascript:;">{{ tag }}</a>
                    {% endfor %}
                </ul>
            </div>
            <div class="guanzhu">
                <h2>关注我 么么哒</h2>
                <ul>
                    <img src="/static/blog/images/wx.jpg">
                </ul>
            </div>
        </aside>
        <main>
            <div class="infosbox">
                <div class="newsview">
                    <h3 class="news_title">{{ article.title }}</h3>
                    <div class="bloginfo">
                        <ul>
                            <li class="author">作者：<a href="/">{{ article.ariticle_user.name }}</a></li>

                            <li class="timer">时间：{{ article.time }}</li>
                            <li class="view">{{ article.visit }}人已阅读</li>
                        </ul>
                    </div>
                    <div class="tags">

                        {% for typecls in typeclass %}
                                   <a href="/" target="_blank">{{ typecls }}</a> &nbsp;
                        {% endfor %}



                    </div>
                    <div class="news_about"><strong>简介</strong>
                        {{ article.introduce }}
                    </div>

                    {{ article.text | safe }}


                </div>


                <div class="share">
                    <p class="diggit" id="thumbs-up"><a
                            href="JavaScript:;">
                        很赞哦！ </a>(<b id="diggnum">
                        {{ article.num }}</b>)
                    </p>

                    <script>


                        $(function () {
                            $("#thumbs-up").click(function () {
                                $.ajax({
                                    url: "",
                                    method: "PUT",
                                    data: {
                                        "id":{{ article.id }}
                                    },
                                    success(data) {
                                        if (data.code == "1") {
                                            $("#thumbs-up").find("b").html(data.art_num);
                                        } else if (data.code == "2") {
                                            alert("不要贪杯哦！！！")
                                        } else if (data.code == "0") {
                                            alert("系统错误！！！")
                                        }
                                    }
                                })
                            })
                        })

                    </script>

                </div>
                <div class="nextinfo">

                    <p>上一篇：

                        {% if prvart == None %}
                            <a href="{{ url_for('blog.home') }}">返回首页</a>                        {% else %}
                            <a href="{{ url_for('blog.info', id=prvart.id) }}">{{ prvart.title }}</a></p>
                        {% endif %}
                    <p>下一篇：
                        {% if nextart == None %}
                            <a href="{{ url_for('blog.home') }}">返回首页</a>
                        {% else %}
                            <a href="{{ url_for('blog.info', id=nextart.id) }}">{{ nextart.title }}</a>
                        {% endif %}
                    </p>

                </div>
                <div class="news_pl">
                    <h2>文章评论</h2>
                    <div class="gbko">
                        <script src="/e/pl/more/?classid=77&amp;id=106&amp;num=20"></script>
                        {% for command in commands %}
                            <div class="fb">
                                <ul>
                                    <p class="fbtime"><span>{{ command.time }}</span>{{ command.comment_user.name }}</p>
                                    <p class="fbinfo">{{ command.info }}</p>
                                </ul>
                            </div>
                        {% endfor %}


                        <script>
                            function CheckPl(obj) {
                                if (obj.saytext.value == "") {
                                    alert("您没什么话要说吗？");
                                    obj.saytext.focus();
                                    return false;
                                }
                                return true;
                            }
                        </script>
                        <form action="" method="post" name="saypl" id="saypl"
                              onsubmit="return CheckPl(document.saypl)">
                            <div id="plpost">
                                <p class="saying"><span><a href="/e/pl/?classid=77&amp;id=106">共有<script
                                        type="text/javascript"
                                        src="/e/public/ViewClick/?classid=77&amp;id=106&amp;down=2"></script>2条评论</a></span>来说两句吧...
                                </p>
                                <p class="yname"><span>用户名:</span>
                                    <input name="username" type="text" class="inputText" id="username" value=""
                                           size="16">
                                </p>
                                <p class="yzm"><span>验证码:</span>
                                    <input name="key" type="text" id="yzminput" class="inputText" size="16">
                                    <span id="yzm"
                                          style="padding-left:10px;border: 1px solid #ccc;text-align: center;font-size: 14px;cursor: pointer;letter-spacing: 3px;">点击获取验证码</span>
                                </p>


                                <input name="nomember" type="hidden" id="nomember" value="{ article.id}}"
                                       checked="checked">
                                <textarea name="saytext" rows="6" id="saytext"></textarea>
                                <input name="imageField" type="submit" value="提交">

                                <script>
                                    $(function () {
                                        let yzmnum = "";
                                        $("#yzm").click(function () {

                                            $.get("/yzm/", function (data) {
                                                console.log(data)
                                                if (data.code == 1) {
                                                    $("#yzm").html(data.yzm)
                                                    yzmnum = data.yzm
                                                }

                                            })

                                        });
                                        $("#saytext").next("input").click(function () {


                                            if ($("#yzminput").val() == "") {
                                                alert("验证码不能呢为空：")
                                                return false
                                            }

                                            console.log("---------" + yzmnum)
                                            console.log($("#yzminput").val(), yzmnum)
                                            if ($("#yzminput").val() != yzmnum) {
                                                alert("输入的验证码有误：")
                                                return false
                                            }


                                            data = {
                                                "artid": {{ article.id }},
                                                "name": $("#username").val(),
                                                "info": $("#saytext").val(),
                                            };


                                            $.post("", data, function (data) {
                                                if (data.code == "1") {
                                                    alert("插入成功");
                                                    location.reload()
                                                } else if (data.code == "2") {
                                                    alert("系统错误。")
                                                }
                                            });
                                            return false
                                        })

                                    })


                                </script>


                            </div>
                        </form>
                    </div>
                </div>


            </div>
        </main>
    </article>
    <footer>
        <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
    </footer>
    <a href="#" class="cd-top">Top</a>

{% endblock %}